"""Initial Migration11

Revision ID: 58eab90fc3f0
Revises: 
Create Date: 2019-02-27 13:45:41.069996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58eab90fc3f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('published_at', sa.DateTime(), nullable=True))
    op.add_column('pitches', sa.Column('downvote', sa.Integer(), nullable=True))
    op.add_column('pitches', sa.Column('pitch_content', sa.String(length=255), nullable=True))
    op.add_column('pitches', sa.Column('published_at', sa.DateTime(), nullable=True))
    op.add_column('pitches', sa.Column('upvote', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'upvote')
    op.drop_column('pitches', 'published_at')
    op.drop_column('pitches', 'pitch_content')
    op.drop_column('pitches', 'downvote')
    op.drop_column('comments', 'published_at')
    # ### end Alembic commands ###
