"""Init1 Migration26

Revision ID: d4c78fe6b102
Revises: 58eab90fc3f0
Create Date: 2019-02-27 19:32:28.797415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4c78fe6b102'
down_revision = '58eab90fc3f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('title', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'title')
    # ### end Alembic commands ###
